### ISSUE TITLE
Always mark Sub-tasks as error when hitting problems 

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisPlatform#1072]
## Issue Description
If `record_sub_task_failure` fails then the status of a sub-task is not marked as ERROR

```
[2024-06-28 11:30:55,412: ERROR/ForkPoolWorker-15] Task record_sub_task_failure[0aa2ad81-e530-4666-9238-c43d843fca90] raised unexpected: AttributeError("'NoneType' object has no attribute 'encode'")
Traceback (most recent call last):
  File "/home/server/.local/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/server/.local/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
  File "/var/www/oasis/src/server/oasisapi/analyses/v2_api/tasks.py", line 632, in record_sub_task_failure
    tmp_file.write(tb.encode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'encode'
```

* Also when this happens --> the main analyses logs are also blank 
* test running a custom lookup class which throws an exception in V2 run mode

**Comment by sambles** [comment]
**Worker:**
```
[2024-07-02 13:49:48,646: INFO/MainProcess] Task prepare_keys_file_chunk[babdf7c0-6dfc-4fc6-bdda-b652ae23d247] received
[2024-07-02 13:49:48,649: INFO/ForkPoolWorker-16] Task prepare_keys_file_chunk[babdf7c0-6dfc-4fc6-bdda-b652ae23d247] retry: Retry in 6s: UnserializableException('This is an Injected error for a custrom lookup class - that cant be serialized?')
[2024-07-02 13:49:48,659: INFO/MainProcess] ???[???]: Task error handler
[2024-07-02 13:49:48,659: ERROR/MainProcess] Signal handler <function handle_task_failure at 0x7fc864b78b80> raised: AttributeError("'NoneType' object has no attribute 'get'")
Traceback (most recent call last):
  File "/home/worker/.local/lib/python3.10/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/worker/src/model_execution_worker/distributed_tasks.py", line 1049, in handle_task_failure
    task_log_file = f"{TASK_LOG_DIR}/{task_args.get('run_data_uuid')}_{task_args.get('slug')}.log"
AttributeError: 'NoneType' object has no attribute 'get'
[2024-07-02 13:49:48,659: ERROR/MainProcess] Task handler raised error: <MaybeEncodingError: Error sending result: ''(1, <ExceptionInfo: ExceptionWithTraceback()>, None)''. Reason: ''TypeError("cannot pickle \'_io.TextIOWrapper\' object")''.>
Traceback (most recent call last):
  File "/home/worker/.local/lib/python3.10/site-packages/billiard/pool.py", line 365, in workloop
    put((READY, (job, i, result, inqW_fd)))
  File "/home/worker/.local/lib/python3.10/site-packages/billiard/queues.py", line 366, in put
    self.send_payload(ForkingPickler.dumps(obj))
  File "/home/worker/.local/lib/python3.10/site-packages/billiard/reduction.py", line 55, in dumps
    cls(buf, protocol).dump(obj)
billiard.pool.MaybeEncodingError: Error sending result: ''(1, <ExceptionInfo: ExceptionWithTraceback()>, None)''. Reason: ''TypeError("cannot pickle \'_io.TextIOWrapper\' object")''.
```


**Worker-monitor**
```
[2024-07-02 13:49:42,636: ERROR/ForkPoolWorker-15] Task record_sub_task_failure[52fb528b-62ec-4e0e-967a-c4903c12d238] raised unexpected: AttributeError("'NoneType' object has no attribute 'encode'")
Traceback (most recent call last):
  File "/home/server/.local/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/server/.local/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
  File "/var/www/oasis/src/server/oasisapi/analyses/v2_api/tasks.py", line 641, in record_sub_task_failure
    tmp_file.write(tb.encode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'encode'
```



Class:

```
from oasislmf.lookup.base import MultiprocLookupMixin
from oasislmf.lookup.interface import KeyLookupInterface
from oasislmf.utils.exceptions import OasisException

class UnserializableException(Exception):
    def __init__(self, message):
        super().__init__(message)
        self.file_handle = open(__file__, 'r')  # Adding a file handle makes it unserializable

class PiCustomKeysLookup(KeyLookupInterface, MultiprocLookupMixin):


    def __init__(self, config, **kwargs):
        pass

    def process_locations(self, loc_df, **kwargs):
        #raise ValueError('This is an Injected error for a custrom lookup class')
        raise UnserializableException('This is an Injected error for a custrom lookup class - that cant be serialized?')
```
