### ISSUE TITLE
Removal of traceback files causes a cascade delete

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisPlatform#262]
**Trace - worker Monitor**
```
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")
[SQL: SELECT celery_taskmeta.id AS celery_taskmeta_id, celery_taskmeta.task_id AS celery_taskmeta_task_id, celery_taskmeta.status AS celery_taskmeta_status, celery_taskmeta.result AS celery_taskmeta_result, celery_taskmeta.date_done AS celery_taskmeta_date_done, celery_taskmeta.traceback AS celery_taskmeta_traceback
FROM celery_taskmeta
WHERE celery_taskmeta.task_id = %(task_id_1)s]
[parameters: {'task_id_1': '24ef72f8-6e14-437f-88ff-6595787d36cf'}]
(Background on this error at: http://sqlalche.me/e/e3q8)
[2019-10-10 18:19:34,369: INFO/MainProcess] Received task: run_analysis_success[586fd2a4-d05f-48fb-8b05-6d7b4f6b830a]
[2019-10-10 18:19:34,370: INFO/ForkPoolWorker-1] run_analysis_success[586fd2a4-d05f-48fb-8b05-6d7b4f6b830a]: output_location: 37f50a5af9a54aa4af94028624329db4.tar, analysis_pk: 2, initiator_pk: 1
[2019-10-10 18:19:34,486: ERROR/ForkPoolWorker-1] run_analysis_success[586fd2a4-d05f-48fb-8b05-6d7b4f6b830a]: save() prohibited to prevent data loss due to unsaved related object 'run_traceback_file'.
Traceback (most recent call last):
  File "/var/www/oasis/src/server/oasisapi/analyses/tasks.py", line 58, in run_analysis_success
    analysis.save()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 693, in save
    "unsaved related object '%s'." % field.name
ValueError: save() prohibited to prevent data loss due to unsaved related object 'run_traceback_file'.
```

https://github.com/OasisLMF/OasisPlatform/blob/develop/src/server/oasisapi/analyses/tasks.py#L55-L56

https://github.com/OasisLMF/OasisPlatform/blob/develop/src/server/oasisapi/analyses/tasks.py#L139-L140

**Comment by sambles** [comment]
Fixed in 1.3.3
449f45dedd537f5398b01c182d8e678b8bee795f 
d2d5ffbef9452cb06035b6fc63332b796ae1b1b2
