### ISSUE TITLE
FM file generation fails in worker (feature/api-upgrade)

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisPlatform#32]
Celery doesn't support calling the multiprocessing library used in FM file generation:
https://github.com/OasisLMF/OasisLMF/blob/master/oasislmf/utils/concurrency.py

Related Issues:
https://github.com/celery/celery/issues/4525
https://github.com/celery/celery/issues/4551
 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/worker/src/model_execution_worker/tasks.py", line 167, in generate_input
    '--fm'
  File "/usr/local/lib/python3.6/site-packages/argparsetree/cmd.py", line 161, in run
    return self.action(args) or 0
  File "/usr/local/lib/python3.6/site-packages/oasislmf/cmd/model.py", line 619, in action
    logger=self.logger
  File "/usr/local/lib/python3.6/site-packages/oasislmf/exposures/manager.py", line 1666, in start_oasis_files_pipeline
    fm_files = self.write_fm_files(oasis_model=oasis_model, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/oasislmf/exposures/manager.py", line 1440, in write_fm_files
    fm_items_df, canacc_df = self.load_fm_items(canexp_df, gul_items_df, canonical_exposures_profile, canonical_accounts_profile, canonical_accounts_file_path, fm_agg_profile)
  File "/usr/local/lib/python3.6/site-packages/oasislmf/exposures/manager.py", line 1141, in load_fm_items
    fm_items = [it for it in self.generate_fm_items(canexp_df, gul_items_df, cep, cap, canacc_df, fmap)]
  File "/usr/local/lib/python3.6/site-packages/oasislmf/exposures/manager.py", line 1141, in <listcomp>
    fm_items = [it for it in self.generate_fm_items(canexp_df, gul_items_df, cep, cap, canacc_df, fmap)]
  File "/usr/local/lib/python3.6/site-packages/oasislmf/exposures/manager.py", line 1034, in generate_fm_items
    for it in multiprocess(concurrent_tasks, pool_size=num_ps):
  File "/usr/local/lib/python3.6/site-packages/oasislmf/utils/concurrency.py", line 164, in multiprocess
    pool = Pool(pool_size)
  File "/usr/local/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 174, in __init__
    self._repopulate_pool()
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 103, in start
    'daemonic processes are not allowed to have children'
AssertionError: daemonic processes are not allowed to have children
```

**Comment by sr-murthy** [comment]
It is a pity but this appears to be a known problem with Celery

https://wiredcraft.com/blog/3-gotchas-for-celery

**Comment by sambles** [comment]
fixed
