### ISSUE TITLE
Migration issue moving from DB of versions `1.1.2` and older 

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisPlatform#325]
```
2020-02-28T13:17:26.668932000Z django.db.utils.OperationalError: (1050, "Table 'analyses_analysis_complex_model_data_files' already exists")
2020-02-28T13:17:27.004836000Z   Applying analyses.0004_analysis_complex_model_data_files...$
```

**Comment by sambles** [comment]
- [ ] Fix migration from older DB
- [ ] Add migration test to CI

Problem occurs when an Inital database was created with version 1.1.2  or older due to conflicting migration files 0002_analysis_complex_model_data_files.py + 0004_analysis_complex_model_data_files.py 

https://github.com/OasisLMF/OasisPlatform/commit/24fd3d0023d262671dcf155f96f31bd43aa7cb92
```
Running migrations:
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying data_files.0001_initial... OK
  Applying data_files.0002_auto_20190704_1403... OK
  Applying analyses.0003_auto_20190625_1006... OK
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1050, "Table 'analyses_analysis_complex_model_data_files' already exists")
```
