### ISSUE TITLE
KTOOLS / Celery - Lock File Timeout after 3 attempts

### ISSUE THREAD

**Issue by lucaspanayiotou** [OasisLMF/OasisPlatform#42]
we are seeing the below error regarding the ktools lock file / celery interaction: 
It is suspected that the queuing works correctly when dealing with multiple requests for the same worker, but when you start throwing other workers in the mix thing fail. 

`[2018-11-26 10:44:21,441: INFO/ForkPoolWorker-1] Task run_analysis[c5d3eaa0-d844-4abd-89e5-24e979b4a91c] retry: Retry in 10s
[2018-11-26 10:44:26,062: INFO/ForkPoolWorker-1] Failed to get resource lock - retry task
[2018-11-26 10:44:26,103: INFO/MainProcess] Received task: run_analysis[c5d3eaa0-d844-4abd-89e5-24e979b4a91c]  ETA:[2018-11-26 10:44:36.063333+00:00]
[2018-11-26 10:44:26,148: INFO/ForkPoolWorker-1] Task run_analysis[c5d3eaa0-d844-4abd-89e5-24e979b4a91c] retry: Retry in 10s
[2018-11-26 10:44:36,066: INFO/ForkPoolWorker-1] Failed to get resource lock - retry task
[2018-11-26 10:44:36,092: INFO/MainProcess] Received task: run_analysis[c5d3eaa0-d844-4abd-89e5-24e979b4a91c]  ETA:[2018-11-26 10:44:46.066567+00:00]
[2018-11-26 10:44:36,094: INFO/ForkPoolWorker-1] Task run_analysis[c5d3eaa0-d844-4abd-89e5-24e979b4a91c] retry: Retry in 10s
[2018-11-26 10:44:46,072: INFO/ForkPoolWorker-1] Failed to get resource lock - retry task
[2018-11-26 10:44:46,178: ERROR/ForkPoolWorker-1] Task run_analysis[c5d3eaa0-d844-4abd-89e5-24e979b4a91c] raised unexpected: MaxRetriesExceededError(u"Can't retry run_analysis[c5d3eaa0-d844-4abd-89e5-24e979b4a91c] args:(u'f69b63a709ad4a7f9a0ff92a47fd97e5', [{u'analysis_settings': {u'gul_summaries': [{u'id': 1, u'aalcalc': True}], u'source_tag': u'UI', u'il_summaries': [], u'analysis_tag': u'1153', u'number_of_samples': 8, u'model_version_id': u'1', u'module_supplier_id': u'ARA', u'gul_threshold': 0, u'gul_output': True, u'exposure_location': u'L:', u'ri_summaries': [], u'prog_id': 1120, u'model_settings': {u'peril_wind': True, u'event_set': u'P', u'demand_surge': True, u'session_id': 767, u'event_occurrence_id': u'1', u'peril_surge': True}}}]) kwargs:{}",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "src/model_execution_worker/tasks.py", line 88, in start_analysis_task
    raise self.retry(countdown=retry_countdown_in_secs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 670, in retry
    self.name, request.id, S.args, S.kwargs))
MaxRetriesExceededError: Can't retry run_analysis[c5d3eaa0-d844-4abd-89e5-24e979b4a91c] args:(u'f69b63a709ad4a7f9a0ff92a47fd97e5', [{u'analysis_settings': {u'gul_summaries': [{u'id': 1, u'aalcalc': True}], u'source_tag': u'UI', u'il_summaries': [], u'analysis_tag': u'1153', u'number_of_samples': 8, u'model_version_id': u'1', u'module_supplier_id': u'ARA', u'gul_threshold': 0, u'gul_output': True, u'exposure_location': u'L:', u'ri_summaries': [], u'prog_id': 1120, u'model_settings': {u'peril_wind': True, u'event_set': u'P', u'demand_surge': True, u'session_id': 767, u'event_occurrence_id': u'1', u'peril_surge': True}}}]) kwargs:{}
[2018-11-26 10:46:37,981: INFO/MainProcess] missed heartbeat from celery@bcd3668c62cb`

**Comment by mpinkerton-oasis** [comment]
I have made a couple of changes in this branch: https://github.com/OasisLMF/OasisPlatform/tree/feature/job_scheduling

- The number of retries due to the lock is now unlimited.
- The retry timeout is set by a parameter "OASIS_LOCK_RETRY_COUNTDOWN_IN_SECS". 30s might be a sensible initial value.

@benhayes21  is going to organize a test deployment.

**Comment by lucaspanayiotou** [comment]
Thanks, we'll discuss how to deploy this change with Ben.

**Comment by mpinkerton-oasis** [comment]
There is an issue that re-queued jobs get put to the pack, so even though the jobs should all complete eventually the order can be weird.

**Comment by mpinkerton-oasis** [comment]
@lucaspanayiotou can you comment on how this worked? We have merged this change into the new build for further testing.

**Comment by lucaspanayiotou** [comment]
I tested this for the MENAEQ worker. I ran multiple jobs, alongs side a MEEQ worker without the implemented fix. What I found was the MEEQ worker failed due to exceeding max retries while the MENAEQ worker completed on every occasion.

I suggested rolling 0.396.0.queue2 out to the rest of the stack but was advised by Ben to just wait for 0.397.0.

**Comment by mpinkerton-oasis** [comment]
@lucaspanayiotou is this okay in 397? Can we close?

**Comment by lucaspanayiotou** [comment]
Ok to close. Thank you

**Comment by lucaspanayiotou** [comment]
I'd like to reopen this issue. 

We have started to see this again. Is this any thing to do with rabbit? If so I will look into our rabbit build as we pull a very old image for this to make the RHEL version...

`[2019-02-04 17:01:01,950: INFO/ForkPoolWorker-1] Task run_analysis[d933848f-58df-4910-a64e-a6dd8a29870d] retry: Retry in 10s
[2019-02-04 17:01:01,950: INFO/MainProcess] Received task: run_analysis[d933848f-58df-4910-a64e-a6dd8a29870d] ETA:[2019-02-04 17:01:11.946082+00:00]
[2019-02-04 17:01:11,952: INFO/ForkPoolWorker-1] LOCK_FILE: /tmp/ktools_lock_file/tmp_ktools_lock_file
[2019-02-04 17:01:11,952: INFO/ForkPoolWorker-1] LOCK_RETRY_COUNTDOWN_IN_SECS: 10
[2019-02-04 17:01:11,953: INFO/ForkPoolWorker-1] Failed to get resource lock - retry task
[2019-02-04 17:01:11,966: ERROR/ForkPoolWorker-1] Task run_analysis[d933848f-58df-4910-a64e-a6dd8a29870d] raised unexpected: MaxRetriesExceededError(u"Can't retry run_analysis[d933848f-58df-4910-a64e-a6dd8a29870d] args:(u'6aeabe38f21a4fb4a39bd494264c1e91', [{u'analysis_settings': {u'gul_summaries': [{u'aalcalc': True, u'pltcalc': True, u'eltcalc': True, u'leccalc': {u'outputs': {u'full_uncertainty_aep': True, u'full_uncertainty_oep': True, u'wheatsheaf_oep': True, u'wheatsheaf_aep': True}, u'return_period_file': True}, u'summarycalc': True, u'id': 1, u'lec_output': True}, {u'id': 2, u'aalcalc': True}], u'source_tag': u'UI', u'il_summaries': [{u'aalcalc': True, u'pltcalc': True, u'eltcalc': True, u'leccalc': {u'outputs': {u'full_uncertainty_aep': True, u'full_uncertainty_oep': True, u'wheatsheaf_oep': True, u'wheatsheaf_aep': True}, u'return_period_file': True}, u'summarycalc': True, u'id': 1, u'lec_output': True}, {u'id': 2, u'aalcalc': True}], u'analysis_tag': u'315', u'number_of_samples': 10, u'model_version_id': u'CAFL_Combined', u'module_supplier_id': u'GuyCarpenter', u'gul_threshold': 0, u'gul_output': True, u'il_output': True, u'exposure_location': u'L:', u'ri_summaries': [{u'aalcalc': True, u'pltcalc': True, u'eltcalc': True, u'leccalc': {u'outputs': {u'full_uncertainty_aep': True, u'full_uncertainty_oep': True, u'wheatsheaf_oep': True, u'wheatsheaf_aep': True}, u'return_period_file': True}, u'summarycalc': True, u'id': 1, u'lec_output': True}, {u'id': 2, u'aalcalc': True}], u'prog_id': 312, u'ri_output': True, u'model_settings': {u'event_set': u'Combined', u'event_occurrence_id': u'Combined', u'peril_flood': True}}}]) kwargs:{}",)
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 382, in trace_task
R = retval = fun(*args, **kwargs)
File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 641, in __protected_call__
return self.run(*args, **kwargs)
File "src/model_execution_worker/tasks.py", line 93, in start_analysis_task
countdown=settings.getint('worker', 'LOCK_RETRY_COUNTDOWN_IN_SECS'))
File "/usr/lib/python2.7/site-packages/celery/app/task.py", line 670, in retry
self.name, request.id, S.args, S.kwargs))
MaxRetriesExceededError: Can't retry run_analysis[d933848f-58df-4910-a64e-a6dd8a29870d] args:(u'6aeabe38f21a4fb4a39bd494264c1e91', [{u'analysis_settings': {u'gul_summaries': [{u'aalcalc': True, u'pltcalc': True, u'eltcalc': True, u'leccalc': {u'outputs': {u'full_uncertainty_aep': True, u'full_uncertainty_oep': True, u'wheatsheaf_oep': True, u'wheatsheaf_aep': True}, u'return_period_file': True}, u'summarycalc': True, u'id': 1, u'lec_output': True}, {u'id': 2, u'aalcalc': True}], u'source_tag': u'UI', u'il_summaries': [{u'aalcalc': True, u'pltcalc': True, u'eltcalc': True, u'leccalc': {u'outputs': {u'full_uncertainty_aep': True, u'full_uncertainty_oep': True, u'wheatsheaf_oep': True, u'wheatsheaf_aep': True}, u'return_period_file': True}, u'summarycalc': True, u'id': 1, u'lec_output': True}, {u'id': 2, u'aalcalc': True}], u'analysis_tag': u'315', u'number_of_samples': 10, u'model_version_id': u'CAFL_Combined', u'module_supplier_id': u'GuyCarpenter', u'gul_threshold': 0, u'gul_output': True, u'il_output': True, u'exposure_location': u'L:', u'ri_summaries': [{u'aalcalc': True, u'pltcalc': True, u'eltcalc': True, u'leccalc': {u'outputs': {u'full_uncertainty_aep': True, u'full_uncertainty_oep': True, u'wheatsheaf_oep': True, u'wheatsheaf_aep': True}, u'return_period_file': True}, u'summarycalc': True, u'id': 1, u'lec_output': True}, {u'id': 2, u'aalcalc': True}], u'prog_id': 312, u'ri_output': True, u'model_settings': {u'event_set': u'Combined', u'event_occurrence_id': u'Combined', u'peril_flood': True}}}]) kwargs:{}
`

**Comment by mpinkerton-oasis** [comment]
Seems like there is an issue with the Celery max_retries. This should be unlimited if set to None, but actually failed after some number. In stead, I set this to a very large number that will not be exceeded in practice.

The relevant settings in the worker compose file are:
- OASIS_LOCK_FILE: the shared lock file
- OASIS_LOCK_RETRY_COUNTDOWN_IN_SECS: the re-post time for a blocked job
- OASIS_LOCK_TIMEOUT_IN_SECS: the initial wait time for a received job
- OASIS_POST_ANALYSIS_SLEEP_IN_SECS: wait at the end of the job, to allow work to be picked up by different workers.

The setting OASIS_MAX_RETRIES is no longer used.

Fix in branch https://github.com/OasisLMF/OasisPlatform/tree/feature/max_retries_issue

**Comment by sdaniel1609** [comment]
Hello @mpinkerton-oasis,

It looks like this issue is reintroduced in coreoasis/model_execution_worker:0.397.9.

`[2019-04-17 11:05:00,664: INFO/MainProcess] Received task: run_analysis[1bbc5252-e2d3-47da-aeb7-8046fd42dca9]
[2019-04-17 11:05:00,665: INFO/ForkPoolWorker-1] LOCK_FILE: /tmp/ktools_lock_file
[2019-04-17 11:05:00,666: INFO/ForkPoolWorker-1] LOCK_RETRY_COUNTDOWN_IN_SECS: 10
[2019-04-17 11:05:00,667: INFO/ForkPoolWorker-1] Acquired resource lock
[2019-04-17 11:05:00,667: INFO/ForkPoolWorker-1] INPUTS_DATA_DIRECTORY: /var/www/oasis/upload
[2019-04-17 11:05:00,667: INFO/ForkPoolWorker-1] OUTPUTS_DATA_DIRECTORY: /var/www/oasis/download
[2019-04-17 11:05:00,667: INFO/ForkPoolWorker-1] MODEL_DATA_DIRECTORY: /var/oasis/model_data
[2019-04-17 11:05:00,668: INFO/ForkPoolWorker-1] WORKING_DIRECTORY: /var/oasis/working
[2019-04-17 11:05:00,668: INFO/ForkPoolWorker-1] KTOOLS_BATCH_COUNT: 24
[2019-04-17 11:05:00,668: INFO/ForkPoolWorker-1] KTOOLS_MEMORY_LIMIT: True
[2019-04-17 11:05:00,678: INFO/ForkPoolWorker-1] STARTED: src.model_execution_worker.tasks.start_analysis
[2019-04-17 11:05:00,691: INFO/ForkPoolWorker-1] Source tag = 1888; Analysis tag: UI
[2019-04-17 11:05:00,692: INFO/ForkPoolWorker-1] Model supplier - version = GuyCarpenter DEHL
[2019-04-17 11:05:00,694: INFO/ForkPoolWorker-1] Setting up analysis working directory
[2019-04-17 11:05:00,740: INFO/ForkPoolWorker-1] Working directory = /var/oasis/working/UI_1888_3c52f3f8d55d492a80dc0d9cfa65c222
[2019-04-17 11:05:00,741: INFO/ForkPoolWorker-1] STARTED: oasislmf.model_execution.runner.run
[2019-04-17 11:05:11,430: INFO/ForkPoolWorker-1] COMPLETED: oasislmf.model_execution.runner.run in 10.69s
[2019-04-17 11:05:25,167: INFO/ForkPoolWorker-1] Output location = eee7d00162f445a89a05b8138dae660e
[2019-04-17 11:05:25,167: INFO/ForkPoolWorker-1] COMPLETED: src.model_execution_worker.tasks.start_analysis in 24.49s
[2019-04-17 11:05:25,179: INFO/ForkPoolWorker-1] Task run_analysis[1bbc5252-e2d3-47da-aeb7-8046fd42dca9] succeeded in 24.513918675s: 'eee7d00162f445a89a05b8138dae660e'
[2019-04-17 16:03:43,891: INFO/MainProcess] Received task: run_analysis[72a0fd8c-a29c-4638-919d-12ae0d284c95]
[2019-04-17 16:03:43,892: INFO/ForkPoolWorker-1] LOCK_FILE: /tmp/ktools_lock_file
[2019-04-17 16:03:43,893: INFO/ForkPoolWorker-1] LOCK_RETRY_COUNTDOWN_IN_SECS: 10
[2019-04-17 16:03:43,894: INFO/ForkPoolWorker-1] Failed to get resource lock - retry task
[2019-04-17 16:03:43,909: INFO/MainProcess] Received task: run_analysis[72a0fd8c-a29c-4638-919d-12ae0d284c95]  ETA:[2019-04-17 17:03:53.895123+01:00]
[2019-04-17 16:03:43,920: INFO/ForkPoolWorker-1] Task run_analysis[72a0fd8c-a29c-4638-919d-12ae0d284c95] retry: Retry in 10s
[2019-04-17 16:03:54,331: INFO/ForkPoolWorker-1] LOCK_FILE: /tmp/ktools_lock_file
[2019-04-17 16:03:54,331: INFO/ForkPoolWorker-1] LOCK_RETRY_COUNTDOWN_IN_SECS: 10
[2019-04-17 16:03:54,332: INFO/ForkPoolWorker-1] Failed to get resource lock - retry task
[2019-04-17 16:03:54,335: INFO/MainProcess] Received task: run_analysis[72a0fd8c-a29c-4638-919d-12ae0d284c95]  ETA:[2019-04-17 17:04:04.333277+01:00]
[2019-04-17 16:03:54,338: INFO/ForkPoolWorker-1] Task run_analysis[72a0fd8c-a29c-4638-919d-12ae0d284c95] retry: Retry in 10s
[2019-04-17 16:04:04,339: INFO/ForkPoolWorker-1] LOCK_FILE: /tmp/ktools_lock_file
[2019-04-17 16:04:04,339: INFO/ForkPoolWorker-1] LOCK_RETRY_COUNTDOWN_IN_SECS: 10
[2019-04-17 16:04:04,340: INFO/ForkPoolWorker-1] Failed to get resource lock - retry task
[2019-04-17 16:04:04,344: INFO/ForkPoolWorker-1] Task run_analysis[72a0fd8c-a29c-4638-919d-12ae0d284c95] retry: Retry in 10s
[2019-04-17 16:04:04,348: INFO/MainProcess] Received task: run_analysis[72a0fd8c-a29c-4638-919d-12ae0d284c95]  ETA:[2019-04-17 17:04:14.341027+01:00]
[2019-04-17 16:04:14,348: INFO/ForkPoolWorker-1] LOCK_FILE: /tmp/ktools_lock_file
[2019-04-17 16:04:14,349: INFO/ForkPoolWorker-1] LOCK_RETRY_COUNTDOWN_IN_SECS: 10
[2019-04-17 16:04:14,349: INFO/ForkPoolWorker-1] Failed to get resource lock - retry task
[2019-04-17 16:04:14,354: WARNING/ForkPoolWorker-1] /usr/local/lib/python2.7/dist-packages/pymysql/cursors.py:170: Warning: (1300, "Invalid utf8mb4 character string: '80027D'")
  result = self._query(query)
[2019-04-17 16:04:14,367: ERROR/ForkPoolWorker-1] Task run_analysis[72a0fd8c-a29c-4638-919d-12ae0d284c95] raised unexpected: MaxRetriesExceededError(u"Can't retry run_analysis[72a0fd8c-a29c-4638-919d-12ae0d284c95] args:(u'2addcff9cbf542318834ddb57a6adb64', [{u'analysis_settings': {u'gul_summaries': [{u'leccalc': {u'outputs': {u'full_uncertainty_aep': True, u'full_uncertainty_oep': True}, u'return_period_file': True}, u'lec_output': True, u'eltcalc': True, u'aalcalc': True, u'id': 1}, {u'eltcalc': True, u'id': 2}], u'source_tag': u'UI', u'il_summaries': [{u'leccalc': {u'outputs': {u'full_uncertainty_aep': True, u'full_uncertainty_oep': True}, u'return_period_file': True}, u'lec_output': True, u'eltcalc': True, u'aalcalc': True, u'id': 1}, {u'eltcalc': True, u'id': 2}], u'analysis_tag': u'1893', u'number_of_samples': 0, u'model_version_id': u'DEHL', u'module_supplier_id': u'GuyCarpenter', u'gul_threshold': 0, u'gul_output': True, u'il_output': True, u'exposure_location': u'L:', u'ri_summaries': [], u'prog_id': 2176, u'model_settings': {}}}]) kwargs:{}",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "src/model_execution_worker/tasks.py", line 94, in start_analysis_task
    countdown=settings.getint('worker', 'LOCK_RETRY_COUNTDOWN_IN_SECS'))
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 707, in retry
    ), task_args=S.args, task_kwargs=S.kwargs
MaxRetriesExceededError: Can't retry run_analysis[72a0fd8c-a29c-4638-919d-12ae0d284c95] args:(u'2addcff9cbf542318834ddb57a6adb64', [{u'analysis_settings': {u'gul_summaries': [{u'leccalc': {u'outputs': {u'full_uncertainty_aep': True, u'full_uncertainty_oep': True}, u'return_period_file': True}, u'lec_output': True, u'eltcalc': True, u'aalcalc': True, u'id': 1}, {u'eltcalc': True, u'id': 2}], u'source_tag': u'UI', u'il_summaries': [{u'leccalc': {u'outputs': {u'full_uncertainty_aep': True, u'full_uncertainty_oep': True}, u'return_period_file': True}, u'lec_output': True, u'eltcalc': True, u'aalcalc': True, u'id': 1}, {u'eltcalc': True, u'id': 2}], u'analysis_tag': u'1893', u'number_of_samples': 0, u'model_version_id': u'DEHL', u'module_supplier_id': u'GuyCarpenter', u'gul_threshold': 0, u'gul_output': True, u'il_output': True, u'exposure_location': u'L:', u'ri_summaries': [], u'prog_id': 2176, u'model_settings': {}}}]) kwargs:{}
`
