### ISSUE TITLE
Swagger UI broken in develop branch

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisPlatform#444]
fails with:
```
Fetch errorInternal Server Error http://localhost:8000/?format=openapi
```

**Comment by sambles** [comment]
Looks to be related to static files: 
```
failed to load SourceMap: Could not load content for http://localhost:8000/static/drf-yasg/swagger-ui-dist/swagger-ui-bundle.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

failed to load SourceMap: Could not load content for http://localhost:8000/static/drf-yasg/swagger-ui-dist/swagger-ui-standalone-preset.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

failed to load SourceMap: Could not load content for http://localhost:8000/static/drf-yasg/swagger-ui-dist/swagger-ui.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by sambles** [comment]
Static files issue was a red herring, `Django==3.1`  breaks the swagger schema (only in the alpine image for some reason). Downgrade to `Django==3.0.11` works but should be investigated and upgraded 

**Traceback**
```
Traceback (most recent call last):
  File "./manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/drf_yasg/management/commands/generate_swagger.py", line 155, in handle
    self.write_schema(schema, self.stdout, format)
  File "/usr/local/lib/python3.8/site-packages/drf_yasg/management/commands/generate_swagger.py", line 79, in write_schema
    swagger_json = codec.encode(schema).decode('utf-8')
  File "/usr/local/lib/python3.8/site-packages/drf_yasg/codecs.py", line 82, in encode
    return force_bytes(self._dump_dict(spec))
  File "/usr/local/lib/python3.8/site-packages/drf_yasg/codecs.py", line 120, in _dump_dict
    out = json.dumps(spec, indent=4, separators=(',', ': '))
  File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.8/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/local/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/local/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.8/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/local/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/lib/python3.8/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/local/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ModelChoiceIteratorValue is not JSON serializable
```


**Pip packages**
```
amqp==5.0.2
asgiref==3.3.0
attrs==20.3.0
billiard==3.6.3.0
boto3==1.16.13
botocore==1.19.13
celery==5.0.2
certifi==2020.11.8
chainmap==1.0.3
chardet==3.0.4
click==7.1.2
click-didyoumean==0.0.3
click-repl==0.1.6
configparser==5.0.1
coreapi==2.3.3
coreschema==0.0.4
decorator==4.4.2
Django==3.1.3
django-cleanup==5.1.0
django-filter==2.4.0
django-model-utils==4.0.0
django-storages==1.10.1
djangorestframework==3.12.2
djangorestframework-simplejwt==4.4.0
drf-yasg==1.20.0
idna==2.10
importlib-metadata==2.0.0
inflection==0.5.1
ipython==5.10.0
ipython-genutils==0.2.0
itypes==1.2.0
Jinja2==2.11.2
jmespath==0.10.0
jsonpickle==1.4.1
jsonschema==3.2.0
kombu==5.0.2
Markdown==3.3.3
MarkupSafe==1.1.1
mysqlclient==2.0.1
packaging==20.4
pathlib2==2.3.5
pexpect==4.8.0
pickleshare==0.7.5
prompt-toolkit==1.0.18
ptyprocess==0.6.0
Pygments==2.5.2
PyJWT==1.7.1
PyMySQL==0.10.1
pyparsing==2.4.7
pyrsistent==0.17.3
python-dateutil==2.8.1
pytz==2020.4
requests==2.24.0
ruamel.yaml==0.16.12
ruamel.yaml.clib==0.2.2
s3transfer==0.3.3
simplegeneric==0.8.1
six==1.15.0
SQLAlchemy==1.3.20
sqlparse==0.4.1
traitlets==4.3.3
uritemplate==3.0.1
urllib3==1.25.11
uWSGI==2.0.19.1
vine==5.0.0
wcwidth==0.2.5
whitenoise==5.2.0
zipp==3.4.0
```
