### ISSUE TITLE
RabbitMQ timeout errors for tasks running over 15mins 

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisPlatform#515]
## Issue Description
**Johan Nilsson:** It looks like rabbitmq have introduced a default consumer timeout on 15 minutes. We updated our rabbitmq (the generic 3-management tag) in one of our environments recently and it looks like this might break celery jobs in the worker longer than 15 minutes (if it is not acked within 15 minutes?). 
https://github.com/rabbitmq/rabbitmq-server/pull/2990 

## Version / Environment information
- RabbitMQ versions **3.8.15** or greater 

## Workaround 
Pin the rabbitMQ container to version `3.8.14`

**docker-compose.yml**
```
  rabbit:
    restart: always
    image: rabbitmq:3.8.14-management                                                                                                        
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
    ports:
      - 5672:5672
      - 15672:15672

```

## Example data / logs
Worker logs contain an error message `PRECONDITION_FAILED - consumer ack timed out on channel <n>`

Example error Trace:
```
  ...
[2021-06-24 11:26:28,939: CRITICAL/MainProcess] Unrecoverable error: PreconditionFailed(406, 'PRECONDITION_FAILED - consumer ack timed out on channel 1', (0, 0), '')
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/root/.local/lib/python3.8/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/root/.local/lib/python3.8/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/root/.local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 311, in start
    blueprint.start(self)
  File "/root/.local/lib/python3.8/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/root/.local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 592, in start
    c.loop(*c.loop_args())
  File "/root/.local/lib/python3.8/site-packages/celery/worker/loops.py", line 81, in asynloop
    next(loop)
  File "/root/.local/lib/python3.8/site-packages/kombu/asynchronous/hub.py", line 361, in create_loop
    cb(*cbargs)
  File "/root/.local/lib/python3.8/site-packages/kombu/transport/base.py", line 235, in on_readable
    reader(loop)
  File "/root/.local/lib/python3.8/site-packages/kombu/transport/base.py", line 217, in _read
    drain_events(timeout=0)
  File "/root/.local/lib/python3.8/site-packages/amqp/connection.py", line 522, in drain_events
    while not self.blocking_read(timeout):
  File "/root/.local/lib/python3.8/site-packages/amqp/connection.py", line 528, in blocking_read
    return self.on_inbound_frame(frame)
  File "/root/.local/lib/python3.8/site-packages/amqp/method_framing.py", line 53, in on_frame
    callback(channel, method_sig, buf, None)
  File "/root/.local/lib/python3.8/site-packages/amqp/connection.py", line 534, in on_inbound_method
    return self.channels[channel_id].dispatch_method(
  File "/root/.local/lib/python3.8/site-packages/amqp/abstract_channel.py", line 143, in dispatch_method
    listener(*args)
  File "/root/.local/lib/python3.8/site-packages/amqp/channel.py", line 277, in _on_close
    raise error_for_code(
amqp.exceptions.PreconditionFailed: (0, 0): (406) PRECONDITION_FAILED - consumer ack timed out on channel 1
```

**Comment by sambles** [comment]
Latest rabbitMQ container (version 3.9.0) seems to exit with: 
```
$ docker logs 75fcd1f4ddd544ccabe1fd49dd26066e_rabbit_1
error: RABBITMQ_DEFAULT_PASS is set but deprecated
error: RABBITMQ_DEFAULT_USER is set but deprecated
error: deprecated environment variables detected

Please use a configuration file instead; visit https://www.rabbitmq.com/configure.html to learn more
```

**Comment by sambles** [comment]
rabbitmq updated version issue - workaround added

**Comment by sambles** [comment]
https://www.rabbitmq.com/docs/consumers#acknowledgement-timeout
