### ISSUE TITLE
Platform 2.0 - On a SubTask error analysis becomes stuck 

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisPlatform#550]
## Issue Description
* SubTask errors need improved handling, like a default retry mechanism
* Better method to mark celery chord as failed on worker lost  

## Steps to Reproduce (Bugs only)
1.  Start multi chunk job (single worker)
2.  Kill one the workers mid execution 
3. Worker recreated by worker-controller 
4. Job 'stuck' as `INPUTS_GENERATION_STARTED` no new chunks are processed on the recreated worker

## Example data / logs
```
 "analysis": {
            "created": "2021-10-14T08:45:21.561539Z",
            "modified": "2021-10-14T09:27:52.943896Z",
            "name": "Analysis_Model_A - Copy",
            "id": 5,
            "portfolio": 1,
            "model": 1,
            "status": "INPUTS_GENERATION_STARTED",
            "task_started": "2021-10-14T09:27:50.854568Z",
            "task_finished": null,
            "complex_model_data_files": [],
            "input_file": null,
            "settings_file": "/v1/analyses/5/settings_file/",
            "settings": "/v1/analyses/5/settings/",
            "lookup_errors_file": null,
            "lookup_success_file": null,
            "lookup_validation_file": null,
            "summary_levels_file": null,
            "input_generation_traceback_file": null,
            "output_file": null,
            "run_traceback_file": null,
            "run_log_file": null,
            "storage_links": "/v1/analyses/5/storage_links/",
            "lookup_chunks": 50,
            "analysis_chunks": 10,
            "sub_task_count": 5,
            "sub_task_statuses": [
               
                 ... 
                
              {
                "task_id": "9cf50a82-61c1-4ea9-b83f-9b78e0c539d3",
                "status": "ERROR",
                "queue_name": "OasisLMF-PiWind-A",
                "name": "Prepare keys file 40",
                "slug": "prepare-keys-file-40",
                "pending_time": "2021-10-14T09:27:50.873623Z",
                "queue_time": "2021-10-14T09:27:53.010740Z",
                "start_time": "2021-10-14T09:35:16.137895Z",
                "end_time": "2021-10-14T09:35:17.174363Z",
                "output_log": null,
                "error_log": "/v1/analysis-task-statuses/362/error_log/"
              },
              .873686Z",
                "queue_time": "2021-10-14T09:27:53.015673Z",
                "start_time": "2021-10-14T09:35:22.384097Z",
                "end_time": "2021-10-14T09:35:23.428742Z",
                "output_log": null,
                "error_log": null
              },
```

```
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'loc_geometry'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3746, in _set_item_mgr
    loc = self._info_axis.get_loc(key)
  File "/root/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'loc_geometry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/celery/app/trace.py", line 450, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/celery/app/trace.py", line 731, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/worker/src/model_execution_worker/distributed_tasks.py", line 398, in run
    return fn(self, params, *args, analysis_id=analysis_id, run_data_uuid=run_data_uuid, **kwargs)
  File "/home/worker/src/model_execution_worker/distributed_tasks.py", line 490, in prepare_keys_file_chunk
    lookup.generate_key_files_singleproc(
  File "/root/.local/lib/python3.8/site-packages/oasislmf/lookup/factory.py", line 430, in generate_key_files_singleproc
    key_results = lookup.process_locations(loc_df)
  File "/root/.local/lib/python3.8/site-packages/oasislmf/lookup/builtin.py", line 209, in process_locations
    locations = step_function(locations)
  File "/root/.local/lib/python3.8/site-packages/oasislmf/lookup/builtin.py", line 372, in fct
    res.append(get_area(locations.loc[locations['peril_id']==peril_id],
  File "/root/.local/lib/python3.8/site-packages/oasislmf/lookup/builtin.py", line 348, in get_area
    gdf_loc["loc_geometry"] = gdf_loc.apply(lambda row: Point(row[f"longitude"], row[f"latitude"]), axis=1)
  File "/root/.local/lib/python3.8/site-packages/geopandas/geodataframe.py", line 1322, in __setitem__
    super(GeoDataFrame, self).__setitem__(key, value)
  File "/root/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3599, in __setitem__
    self._set_item_frame_value(key, value)
  File "/root/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3737, in _set_item_frame_value
    self._set_item_mgr(key, arraylike)
  File "/root/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3749, in _set_item_mgr
    self._mgr.insert(len(self._info_axis), key, value)
  File "/root/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 1158, in insert
    block = new_block(values=value, ndim=self.ndim, placement=slice(loc, loc + 1))
  File "/root/.local/lib/python3.8/site-packages/pandas/core/internals/blocks.py", line 1922, in new_block
    check_ndim(values, placement, ndim)
  File "/root/.local/lib/python3.8/site-packages/pandas/core/internals/blocks.py", line 1964, in check_ndim
    raise ValueError(
ValueError: Wrong number of items passed 9, placement implies 1
```

**Comment by sambles** [comment]
fixed
