### ISSUE TITLE
Platform 2.0 - Analysis copy delete error

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisPlatform#552]
## Issue Description
Same issue as https://github.com/OasisLMF/OasisPlatform/pull/405  fix needs porting over to platform 2.0 branch

Detail, when an analysis is copied the new copy is connected to same RelatedFile Object, if either is deleted that Object is removed leading to: 

```
Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.ForeignKeyViolation: insert or update on table "analyses_analysis" violates foreign key constraint "analyses_analysis_settings_file_id_9e62fbb4_fk_files_rel"
DETAIL:  Key (settings_file_id)=(20) is not present in table "files_relatedfile".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/celery/app/trace.py", line 450, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/root/.local/lib/python3.9/site-packages/celery/app/trace.py", line 731, in __protected_call__
    return self.run(*args, **kwargs)
  File "/var/www/oasis/src/server/oasisapi/analyses/tasks.py", line 334, in start_loss_generation_task
    get_analysis_task_controller().generate_losses(analysis, initiator)
  File "/var/www/oasis/src/server/oasisapi/analyses/task_controller.py", line 487, in generate_losses
    analysis.save()
  File "/root/.local/lib/python3.9/site-packages/model_utils/models.py", line 38, in save
    super().save(*args, **kwargs)
  File "/root/.local/lib/python3.9/site-packages/django/db/models/base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/root/.local/lib/python3.9/site-packages/django/db/models/base.py", line 763, in save_base
    updated = self._save_table(
  File "/root/.local/lib/python3.9/site-packages/django/db/models/base.py", line 845, in _save_table
    updated = self._do_update(base_qs, using, pk_val, values, update_fields,
  File "/root/.local/lib/python3.9/site-packages/django/db/models/base.py", line 899, in _do_update
    return filtered._update(values) > 0
  File "/root/.local/lib/python3.9/site-packages/django/db/models/query.py", line 802, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/root/.local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1559, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/root/.local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: insert or update on table "analyses_analysis" violates foreign key constraint "analyses_analysis_settings_file_id_9e62fbb4_fk_files_rel"
DETAIL:  Key (settings_file_id)=(20) is not present in table "files_relatedfile".

```

**Comment by sambles** [comment]
No longer an issue after rebase/updates
