### ISSUE TITLE
Linking portfolio files on S3 does not work

### ISSUE THREAD

**Issue by johanxnilsson** [OasisLMF/OasisPlatform#593]
## Issue Description

We are using the portfolio storage link endpoints to link our files to a portfolio but it returns a 500 in 1.23.3. The server log looks like this:

```
DEBUG 2022-01-21 14:42:58,681 http_protocol 51 140044503402304 HTTP b'POST' request for ['127.0.0.1', 51588]
DEBUG 2022-01-21 14:42:58,682 selector_events 51 140043845580544 Using selector: EpollSelector
ERROR 2022-01-21 14:42:58,864 log 51 140043835090688 Internal Server Error: /v1/portfolios/1340/storage_links/
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/asgiref/sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/.local/lib/python3.8/site-packages/asgiref/sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/root/.local/lib/python3.8/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/.local/lib/python3.8/site-packages/asgiref/sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
File "/root/.local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/.local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/root/.local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/oasis/./src/server/oasisapi/portfolios/viewsets.py", line 155, in storage_links
    serializer.save()
  File "/root/.local/lib/python3.8/site-packages/rest_framework/serializers.py", line 200, in save
    self.instance = self.update(self.instance, validated_data)
  File "/var/www/oasis/./src/server/oasisapi/portfolios/serializers.py", line 253, in update
    content_type = self.get_content_type(validated_data[field])
  File "/var/www/oasis/./src/server/oasisapi/portfolios/serializers.py", line 247, in get_content_type
    return RelatedFile.objects.get(file=stored_filename).content_type
  File "/root/.local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
src.server.oasisapi.files.models.RelatedFile.DoesNotExist: RelatedFile matching query does not exist.
INFO 2022-01-21 14:42:58,865 middleware 51 140043845580544 POST /v1/portfolios/1340/storage_links/
ERROR 2022-01-21 14:42:58,865 middleware 51 140043845580544 {'Host': 'localhost:8001', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0', 'Accept': 'application/json', 'Accept-Language': 'en-GB,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Referer': 'http://localhost:8001/', 'Content-Type': 'application/json', 'X-Csrftoken': '7oTMUA4rortyD1QzNqrOklyyWmMzJNJG6T1twMLgekyqJ1azIAsLuxuHtyYqC0AD', 'Origin': 'http://localhost:8001', 'Content-Length': '190', 'Connection': 'keep-alive', 'Cookie': 'csrftoken=q2UHEAG1i0rcHvQxgnwH0GNThozyAIpHpx2ogMnQ8Tw4NvaxbxxEaSJ2OALptVgE; OAuth_Token_Request_State=d748d6ed-ddfc-47fd-8c40-e576a9c3ce06; sessionid=8muzte8osa1x0knh76dnavccoxbzykma', 'Sec-Fetch-Dest': 'empty', 'Sec-Fetch-Mode': 'cors', 'Sec-Fetch-Site': 'same-origin'}
ERROR 2022-01-21 14:42:58,865 middleware 51 140043845580544 b'{\n  "accounts_file": "oasis/server/1340_oed_location_bbe65df8-785c-462e-ac41-ea1489b2b44e.csv",\n  "location_file": "oasis/server/1340_oed_location_bbe65df8-785c-462e-ac41-ea1489b2b44e.csv"\n}'
INFO 2022-01-21 14:42:58,866 middleware 51 140043845580544 POST /v1/portfolios/1340/storage_links/ - 500
DEBUG 2022-01-21 14:42:58,866 http_protocol 51 140044503402304 HTTP 500 response started for ['127.0.0.1', 51588]
DEBUG 2022-01-21 14:42:58,867 http_protocol 51 140044503402304 HTTP close for ['127.0.0.1', 51588]
DEBUG 2022-01-21 14:42:58,867 http_protocol 51 140044503402304 HTTP response complete for ['127.0.0.1', 51588]
```

This example use AWS S3 as file storage. Can you try to reproduce this on your side? I have not checked the code, but let me know if you need me to check/test something.

## Steps to Reproduce (Bugs only)
1. Create portfolio
2. Create a file in storage
3. Link it by using `/v1/portfolios/x/storage_links/`

**Comment by sambles** [comment]
This bug looks to be linked to the **OASIS_AWS_LOCATION** option. Testing locally seems to show that linking `<file_hash>.csv` works, but fails when setting `OASIS_AWS_LOCATION=oasis/server` where the S3 object keys are  `oasis/server/<file_hash>.csv`
