### ISSUE TITLE
Cancellation error trace in worker 

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisPlatform#623]
Needs check for chain work around (no tasks to revoke? ) - possibly not a problem but should be looked at 

```
[2022-05-18 11:51:19,894: ERROR/MainProcess] Signal handler <function revoked_handler at 0x7feb005b21f0> raised: TypeError("'NoneType' object does not support item assignment")
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/worker/src/model_execution_worker/distributed_tasks.py", line 175, in revoked_handler
    request.chain[:] = []
```

**Comment by sambles** [comment]
This error leads to ktools processes running in background since the kill task doesn't complete 
![Screenshot from 2022-05-26 08-11-58](https://user-images.githubusercontent.com/9889973/170437144-3054d05e-b072-4291-b35e-799e746e121d.png)
