### ISSUE TITLE
Task cancellation not working correctly for 2.x.x

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisPlatform#797]
## Issue Description
After cancelling a running analysis on Platform 2.1.1+ the analysis is marked as cancelled, but the processes / sub-tasks continue to run on the worker. 

This is from a problem in the task Revoke handler 

```
[2023-04-25 09:09:44,014: ERROR/MainProcess] Signal handler <function revoked_handler at 0x7f39dfc6b1f0> raised: TypeError("'NoneType' object does not support item assignment")
Traceback (most recent call last):
  File "/home/worker/.local/lib/python3.8/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/worker/src/model_execution_worker/distributed_tasks.py", line 229, in revoked_handler
    request.chain[:] = []
TypeError: 'NoneType' object does not support item assignment
[2023-04-25 09:09:44,015: INFO/MainProcess] Terminating 98e4dae7-2cb4-43c7-950b-8831a3e3717b (Signals.SIGTERM)
[2023-04-25 09:09:44,201: ERROR/MainProcess] Signal handler <function revoked_handler at 0x7f39dfc6b1f0> raised: TypeError("'NoneType' object does not support item assignment")
Traceback (most recent call last):
  File "/home/worker/.local/lib/python3.8/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/worker/src/model_execution_worker/distributed_tasks.py", line 229, in revoked_handler
    request.chain[:] = []
TypeError: 'NoneType' object does not support item assignment
[2023-04-25 09:09:45,702: ERROR/ForkPoolWorker-48] Chord 'c8022bae-d083-462d-a150-10ce124774b6' raised: TaskRevokedError('terminated')
Traceback (most recent call last):
  File "/home/worker/.local/lib/python3.8/site-packages/celery/app/builtins.py", line 78, in unlock_chord
    ret = j(
  File "/home/worker/.local/lib/python3.8/site-packages/celery/result.py", line 747, in join
    value = result.get(
  File "/home/worker/.local/lib/python3.8/site-packages/celery/result.py", line 220, in get
    self.maybe_throw(callback=callback)
  File "/home/worker/.local/lib/python3.8/site-packages/celery/result.py", line 336, in maybe_throw
    self.throw(value, self._to_remote_traceback(tb))
  File "/home/worker/.local/lib/python3.8/site-packages/celery/result.py", line 329, in throw
    self.on_ready.throw(*args, **kwargs)
  File "/home/worker/.local/lib/python3.8/site-packages/vine/promises.py", line 234, in throw
    reraise(type(exc), exc, tb)
  File "/home/worker/.local/lib/python3.8/site-packages/vine/utils.py", line 30, in reraise
    raise value
celery.exceptions.TaskRevokedError: terminated

```

> Related note: Tasks hitting OOM can get stuck in a INPUT_GENERATION_STARTED state and never complete. Investigate as connected problem

**Comment by sambles** [comment]
Related note: Tasks hitting OOM can get stuck in a `INPUT_GENERATION_STARTED` state and never complete. 

Investigate as connected problem
