### ISSUE TITLE
Platform 2 fails to find keys data stored in S3 

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisPlatform#866]
## Issue Description
When  S3 is used as backend storage, the file generation fails even though the keys step completed without errors.
```
raised unexpected: OasisException('The path /tmp/run/analysis-17_files-505feaa578ae4873af6354b679258466/keys.csv (Pre-generated keys CSV file path) must exist for Computation Step GenerateFiles')
Traceback (most recent call last):
  File "/home/worker/.local/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/worker/.local/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/worker/.local/lib/python3.10/site-packages/celery/app/autoretry.py", line 60, in run
    ret = task.retry(exc=exc, **retry_kwargs)
  File "/home/worker/.local/lib/python3.10/site-packages/celery/app/task.py", line 736, in retry
    raise_with_context(exc)
  File "/home/worker/.local/lib/python3.10/site-packages/celery/app/autoretry.py", line 38, in run
    return task._orig_run(*args, **kwargs)
  File "/home/worker/src/model_execution_worker/distributed_tasks.py", line 541, in run
    return fn(self, params, *args, analysis_id=analysis_id, run_data_uuid=run_data_uuid, **kwargs)
  File "/home/worker/src/model_execution_worker/distributed_tasks.py", line 794, in write_input_files
    OasisManager().generate_files(**params)
  File "/home/worker/.local/lib/python3.10/site-packages/oasislmf/utils/log.py", line 123, in wrapper
    result = func(*args, **kwargs)
  File "/home/worker/.local/lib/python3.10/site-packages/oasislmf/manager.py", line 86, in interface
    return computation_cls(**kwargs).run()
  File "/home/worker/.local/lib/python3.10/site-packages/oasislmf/computation/base.py", line 56, in __init__
    raise OasisException(
```

> **Note:** Needs investigating

**Comment by sambles** [comment]
data related -- not a bug
