### ISSUE TITLE
Worker Controller crashing under heavy load 

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisPlatform#869]
## Issue Description
**Generate losses running as:** 
* 200 analysis chunks 
* across 35 workers

**Node Sizes** 
* Platform is running on `Standard_D8s_v3`
* Worker `Standard_E8ads_v5`  (limited to 4 chunks per worker) 

 
## Example data / logs
```
2023-08-04 08:22:35,549 INFO: Analysis for model xxx-xxx-xxx is running                                                     

2023-08-04 08:22:36,125 INFO: Total desired number of workers: 35
2023-08-04 08:22:36,126 ERROR: Connection to oasis-websocket:8001 was closed
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 956, in transfer_data
    await asyncio.shield(self._put_message_waiter)
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/worker-controller/oasis_websocket.py", line 87, in watch
    async for msg in next_msg(socket):
  File "/app/worker-controller/oasis_websocket.py", line 53, in next_msg
    while msg := await socket.recv():
  File "/usr/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 553, in recv
    await self.ensure_open()
  File "/usr/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 921, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
Stream closed EOF for oasis-enterprise-preprod/oasis-worker-controller-xxxx (main)
```

**Comment by sambles** [comment]
Issue duplicated, happens when multiple parallel analysis are running also look at 
> Worker pods (and nodes) don't always scale up or down when an analysis starts or stops. There may be a logical explanation but for now it feels unpredictable.

**Comment by sambles** [comment]
After split, connection error still happening on HTTP:   
```
2023-09-20 11:56:21,166 ERROR: Connection to oasis-server:8000 was closed
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 956, in transfer_data
    await asyncio.shield(self._put_message_waiter)
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/worker-controller/oasis_websocket.py", line 88, in watch
    async for msg in next_msg(socket):
  File "/app/worker-controller/oasis_websocket.py", line 54, in next_msg
    while msg := await socket.recv():
  File "/usr/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 553, in recv
    await self.ensure_open()
  File "/usr/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 930, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
2023-09-20 11:56:21,168 ERROR: Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f0d9af7ebc0>
```

**Comment by sambles** [comment]
https://websockets.readthedocs.io/en/stable/faq/common.html#what-does-connectionclosederror-sent-1011-unexpected-error-keepalive-ping-timeout-no-close-frame-received-mean

**Comment by sambles** [comment]
[Code 1011](https://websockets.readthedocs.io/en/stable/topics/timeouts.html#keepalive-in-websockets) - WS Latency check failed 
[Code 1009](https://websockets.readthedocs.io/en/stable/reference/asyncio/common.html#module-websockets.legacy.protocol) - WS Max message size of 1MiB exceeded

**Comment by sambles** [comment]
```
2023-09-20 12:41:24,491 ERROR: Connection to oasis-websocket:8001 was closed
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 945, in transfer_data
    message = await self.read_message()
  File "/usr/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1015, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/usr/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1090, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/usr/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1145, in read_frame
    frame = await Frame.read(
  File "/usr/lib/python3.10/site-packages/websockets/legacy/framing.py", line 70, in read
    data = await reader(2)
  File "/usr/lib/python3.10/asyncio/streams.py", line 697, in readexactly
    raise self._exception
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 862, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/worker-controller/oasis_websocket.py", line 97, in watch
    async for msg in next_msg(socket):
  File "/app/worker-controller/oasis_websocket.py", line 63, in next_msg
    while msg := await socket.recv():
  File "/usr/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 553, in recv
    await self.ensure_open()
  File "/usr/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 921, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
```

**Comment by sambles** [comment]
This check: 
https://github.com/OasisLMF/OasisPlatform/blob/a9ca30ef290f1ed009461b3c3ad1001d19e98f94/kubernetes/worker-controller/src/autoscaler_rules.py#L37-L43 

Doesn't take other running analysis into account,  If 20 worker nodes are executing an a new analysis is added requesting 1 node on the same worker queue, then the replica set is overwritten with `1` killing 19 workers mid execution.

**Comment by sambles** [comment]
The Websocket's dispatched data is wrong, see ` "pending_count": 1`,  `queued_count": 0` and `"running_count": 1`

https://github.com/OasisLMF/OasisPlatform/blob/a9ca30ef290f1ed009461b3c3ad1001d19e98f94/src/server/oasisapi/queues/utils.py#L86-L121

These should be the total of ALL running tasks across analyses.. for some reason they are reading as either `1` or `0`

--> Split this into new issue, looks a bigger problem

```
2023-09-22 14:44:17,322 DEBUG: Socket message: {
    "time": "2023-09-22T13:44:17.318004Z",
    "type": "queue_status.updated",
    "status": "SUCCESS",
    "content": [
        {
            "queue": {
                "name": "OasisLMF-PiWind-1",
                "pending_count": 1,
                "worker_count": 13,
                "queued_count": 0,
                "running_count": 1,
                "models": [
                    {
                        "id": 1,
                        "supplier_id": "OasisLMF",
                        "model_id": "PiWind",
                        "version_id": "1",
                        "created": "2023-09-22T10:32:19.111903Z",
                        "modified": "2023-09-22T11:43:58.855209Z",
                        "data_files": [],
                        "resource_file": "/v1/models/1/resource_file/",
                        "settings": "/v1/models/1/settings/",
                        "versions": "/v1/models/1/versions/",
                        "scaling_configuration": "/v1/models/1/scaling_configuration/",
                        "chunking_configuration": "/v1/models/1/chunking_configuration/",
                        "groups": []
                    }
                ]
            },
            "analyses": [
                {
                    "analysis": {
                        "name": "Analysis_22092023-144351",
                        "id": 18,
                        "portfolio": 18,
                        "model": 1,
                        "status": "RUN_STARTED",
                        "priority": 4,
                        "analysis_chunks": 12,
                        "lookup_chunks": 1,
                        "sub_task_count": 17,
                        "queue_names": [
                            "OasisLMF-PiWind-1",
                            "celery"
                        ],
                        "status_count": {
                            "TOTAL_IN_QUEUE": 15,
                            "TOTAL": 17,
                            "PENDING": 3,
                            "QUEUED": 0,
                            "STARTED": 12,
                            "COMPLETED": 2,
                            "CANCELLED": 0,
                            "ERROR": 0
                        }

```
