### ISSUE TITLE
Error loading model_settings on post to run

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisPlatform#959]
**IMPORTANT: Please apply the relevant labels, for example if this issue is needed as a backported fix add the label `LTS fix` (Long term support fix)

## Issue Description
> Getting the following errors randomly when posting an analysis run request to Oasis server 

model_setting.json exists in the filestore but read fails when validating run

##  Error Logs
```
Traceback (most recent call last):
  File "/home/server/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/server/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/server/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/server/.local/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/server/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/server/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/server/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc 
  File "/home/server/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/oasis/src/server/oasisapi/analyses/viewsets.py", line 271, in run 
    obj.run(request.user)
  File "/var/www/oasis/src/server/oasisapi/analyses/models.py", line 345, in run 
    self.validate_run()
  File "/var/www/oasis/src/server/oasisapi/analyses/models.py", line 312, in validate_run
    model_settings = self.model.resource_file.read_json()
  File "/var/www/oasis/src/server/oasisapi/files/models.py", line 101, in read_json
    self.file.seek(0)
  File "/home/server/.local/lib/python3.10/site-packages/django/core/files/utils.py", line 46, in <lambda>
    seek = property(lambda self: self.file.seek)
  File "/home/server/.local/lib/python3.10/site-packages/django/db/models/fields/files.py", line 45, in _get_file
    self._file = self.storage.open(self.name, 'rb')
  File "/home/server/.local/lib/python3.10/site-packages/django/core/files/storage.py", line 38, in open
    return self._open(name, mode)
  File "/home/server/.local/lib/python3.10/site-packages/django/core/files/storage.py", line 243, in _open
    return File(open(self.path(name), mode))
 
Exception Type: FileNotFoundError at /v1/analyses/8615/run/
Exception Value: [Errno 2] No such file or directory: '/shared-fs/fa855a01dab74c0bab8a1965b1b07f50.json' 
```

## Version / Environment information
- release/2.1.3

**Comment by benhayes21** [comment]
duplicate of #970 
closing
