### ISSUE TITLE
Error when linking S3 object to portfolio

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisPlatform#980]
## Issue Description
When posting an update to an existing portfolio `POST /v2/portfolios/{id}/storage_links/`
```
{
  "accounts_file": "792d7aae18c643219a8d719315cbab0c.csv"
}
```

## Version / Environment information
`2.3.0`

## Example data / logs
```
Traceback (most recent call last):
  File "/home/server/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/server/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/server/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/server/.local/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/server/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/server/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/server/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/server/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/oasis/src/server/oasisapi/portfolios/v2_api/viewsets.py", line 165, in storage_links
    serializer.save()
  File "/home/server/.local/lib/python3.10/site-packages/rest_framework/serializers.py", line 207, in save
    self.instance = self.update(self.instance, validated_data)
  File "/var/www/oasis/src/server/oasisapi/portfolios/v2_api/serializers.py", line 340, in update
    stored_file = default_storage.open(new_related_file.file.name)
  File "/home/server/.local/lib/python3.10/site-packages/django/core/files/storage.py", line 38, in open
    return self._open(name, mode)
  File "/home/server/.local/lib/python3.10/site-packages/storages/backends/s3boto3.py", line 422, in _open
    name = self._normalize_name(clean_name(name))
  File "/home/server/.local/lib/python3.10/site-packages/storages/utils.py", line 43, in clean_name
    clean_name = posixpath.normpath(name).replace('\\', '/')
  File "/usr/lib/python3.10/posixpath.py", line 340, in normpath
    path = os.fspath(path)
```

**Comment by sambles** [comment]
Must be from https://github.com/OasisLMF/OasisPlatform/pull/950
